# Generated by Django 5.2 on 2026-02-18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0011_optimize_integer_field_sizes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this integration",
                        max_length=256,
                        verbose_name="name",
                    ),
                ),
                (
                    "provider_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Documenso (Signature)"),
                            (2, "Digiposte (Digital Vault)"),
                            (99, "Custom Integration"),
                        ],
                        default=99,
                        verbose_name="provider type",
                    ),
                ),
                (
                    "api_url",
                    models.CharField(
                        help_text="Base URL for the provider's API",
                        max_length=512,
                        verbose_name="API URL",
                    ),
                ),
                (
                    "credentials",
                    models.JSONField(
                        blank=True,
                        help_text="Encrypted credentials storage (API keys, tokens, OAuth2 credentials)",
                        null=True,
                        verbose_name="credentials",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Enable/disable this integration without deletion",
                        verbose_name="is active",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="modified",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "integration",
                "verbose_name_plural": "integrations",
                "ordering": ("name",),
            },
        ),
        migrations.AddConstraint(
            model_name="integration",
            constraint=models.UniqueConstraint(
                fields=("name", "owner"),
                name="documents_integration_unique_name_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="integration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("owner__isnull", True)),
                fields=("name",),
                name="documents_integration_name_unique",
            ),
        ),
    ]
